name: Sync Release to Gitee

on:
  release:
    types: [published]

jobs:
  sync-release:
    name: Sync GitHub Release to Gitee
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Download release2gitee
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/hepengju/release2gitee/releases/download/v1.2.2/release2gitee-x86_64-pc-windows-msvc.zip" `
            -OutFile "release2gitee.zip"

      - name: Unzip
        shell: pwsh
        run: |
          Expand-Archive -Path "release2gitee.zip" -DestinationPath "." -Force

      - name: Run release2gitee
        shell: pwsh
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitee_token: ${{ secrets.GITEE_TOKEN }}
        run: |
          $Exe = ".\release2gitee.exe"
          & $Exe `
            --github-owner ${{ github.repository_owner }} `
            --github-repo ${{ github.event.repository.name }} `
            --github-token $env:github_token `
            --gitee-owner ${{ github.repository_owner }} `
            --gitee-repo ${{ github.event.repository.name }} `
            --gitee-token $env:gitee_token `
            --gitee-branch main `
            --github-latest-release-count 30 `
            --gitee-retain-release-attach-files-count 1 `
            --release-body-url-replace `
            --latest-json-url-replace `
            -v