name: Sync Release to Gitee

on:
  release:
    types: [published]

jobs:
  sync-release:
    name: Sync GitHub Release to Gitee
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Sync GitHub Release to Gitee
        uses: trustedinster/sync-release-gitee@v1.3
        with:
          gitee_owner: ch3ngyz
          gitee_repo: Overcooked-2-MOD-Manager-Releases
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          github_owner: ${{ github.repository_owner }}
          github_repo: ${{ github.event.repository.name }}
          gitee_upload_retry_times: 3
          debug: false